export const LANGUAGES = [
  { locale: 'en', name: 'English', flag: 'uk' },
  { locale: 'fr', name: 'Français', flag: 'france' },
  { locale: 'es', name: 'Español', flag: 'spain' },
  { locale: 'de', name: 'Deutsch', flag: 'germany' },
  { locale: 'it', name: 'Italiano', flag: 'italy' },
  { locale: 'pt', name: 'Português', flag: 'portugal' },
  { locale: 'ru', name: 'Русский', flag: 'russia' },
  { locale: 'zh', name: '中文', flag: 'china' },
  { locale: 'ms', name: 'Malaysia', flag: 'malaysia' },
  { locale: 'ja', name: '日本語', flag: 'japan' },
  { locale: 'ko', name: '한국어', flag: 'south-korea' },
  { locale: 'cs', name: 'Čeština', flag: 'czech-republic' },
  { locale: 'da', name: 'Dansk', flag: 'denmark' },
  { locale: 'el', name: 'Ελληνικά', flag: 'greece' },
  { locale: 'fi', name: 'Suomi', flag: 'finland' },
  { locale: 'he', name: 'עברית', flag: 'israel' },
  { locale: 'hi', name: 'हिन्दी', flag: 'india' },
  { locale: 'hu', name: 'Magyar', flag: 'hungary' },
  { locale: 'id', name: 'Bahasa Indonesia', flag: 'indonesia' },
  { locale: 'nb', name: 'Norsk', flag: 'norway' },
  { locale: 'nl', name: 'Nederlands', flag: 'netherlands' },
  { locale: 'pl', name: 'Polski', flag: 'poland' },
  { locale: 'sv', name: 'Svenska', flag: 'sweden' },
  { locale: 'th', name: 'ภาษาไทย', flag: 'thailand' },
  { locale: 'tr', name: 'Türkçe', flag: 'turkey' },
  { locale: 'vi', name: 'Tiếng Việt', flag: 'vietnam' },
];

export const DEFAULT_LANG = 'en';
